version: '3.1'

services:

  db:
    image: wojtekmat/test-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./db_data/:/db_data/
      - ./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
