FROM ubuntu:focal

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y g++ libmysqlclient-dev libmysql++-dev cmake && rm -rf /var/lib/apt/lists/*

WORKDIR /home/sql-injection/

COPY . .

RUN rm -rf build && mkdir build && cd build && cmake .. && make

CMD [ "/home/sql-injection/build/sql-injection" ]
